const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getApiKeys: () => ipcRenderer.invoke('get-api-keys'),
  saveApiKeys: (keys) => ipcRenderer.send('save-api-keys', keys),
  getUserNiches: () => ipcRenderer.invoke('get-user-niches'),
  saveUserNiches: (niches) => ipcRenderer.send('save-user-niches', niches),
  getWatchedFolderPath: () => ipcRenderer.invoke('get-watched-folder-path'),
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  generatePrompt: ({ sub }) => ipcRenderer.invoke("generate-prompt", { sub }),
  onNewVideo: (callback) => ipcRenderer.on('new-video-found', (_event, value) => callback(value)),
  generateMetadataAndCsv: (payload) => ipcRenderer.invoke('generate-metadata-and-csv', payload),
  saveCsv: (csvData) => ipcRenderer.invoke('save-csv', csvData),
  generateBatchPrompts: (payload) => ipcRenderer.invoke('generate-batch-prompts', payload),
  saveBatchPromptsCsv: (data) => ipcRenderer.invoke('save-batch-prompts-csv', data),
  clearUsedSubjects: () => ipcRenderer.send('clear-used-subjects'),
  onSetTheme: (callback) => ipcRenderer.on('set-theme', (_event, theme) => callback(theme)),
  onUpdateAvailable: (callback) => ipcRenderer.on('update_available', (_event, info) => callback(info)),
  onDownloadProgress: (callback) => ipcRenderer.on('download_progress', (_event, percent) => callback(percent)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update_downloaded', (_event) => callback()),
  onDownloadError: (callback) => ipcRenderer.on('download_error', (_event, error) => callback(error)),
  startDownload: () => ipcRenderer.send('start_download'),
  restartApp: () => ipcRenderer.send('restart_app'),
});